#!/bin/bash
# Leverage the 'watch' program to keep an eye on hardirqs and softirqs !

is_gui_supported()
{
 local GUI_MODE=0
 xdpyinfo >/dev/null 2>&1 && GUI_MODE=1
 # On Fedora (26), xdpyinfo fails when run as root; so lets do another check as well
 ps -e|egrep -w "X|Xorg|Xwayland" >/dev/null 2>&1 && GUI_MODE=1 || GUI_MODE=0
 #echo "GUI_MODE $GUI_MODE"
 echo ${GUI_MODE}
}

#--- main

GUI_MODE=$(is_gui_supported)
echo "Detected GUI mode as ${GUI_MODE}"
[[ ${GUI_MODE} -eq 1 ]] && echo "(FYI, if you'd like to run in console mode, rerun passing '-c' to this script)"

[[ $# -eq 1 ]] && [[ "$1" = "-c" ]] && {
   echo "-c passed, forcing console mode..."
   GUI_MODE=0  # -c: console mode
}

TIME_INTV=0.1  # seconds
PROMPT="[Enter] to continue and then ^C to abort..."
title1="Watch : /proc/interrupts : every ${TIME_INTV}s"
cmd1="watch -n${TIME_INTV} -d \"cat /proc/interrupts\""
# On platforms where there are too many IRQs to see on a single screen (like
# the PocketBeagle 2, for one, can try a command like this:
#  watch -n.1 -d "sort -k6 /proc/interrupts"
if [[ ${GUI_MODE} -eq 1 ]] ; then
   echo "GUI mode"
   lxterminal --working-directory=${HOME}/ --command="${cmd1}" --title="${title1}" --geometry=1600x750 &
else
  read -p ">>> ${title1} : ${PROMPT}"
  eval "${cmd1}"
fi

title2="Watch : /proc/softirqs : every 1s"
cmd2="watch -n${TIME_INTV} -d \"cat /proc/softirqs\""
if [[ ${GUI_MODE} -eq 1 ]] ; then
   lxterminal --working-directory=${HOME}/ --command="${cmd2}" --title="${title2}" --geometry=1200x350 &
else
  read -p ">>> ${title2} : ${PROMPT}"
  eval "${cmd2}"
fi
exit 0
