#!/bin/bash
# We expect that the default driver for USB HID devices - usbhid - will take
# over our device.. Here, we want to drive our device via our driver.
# Hence, we identify it's USB bus address (by scanning for the given VID:PID)
# and then unbind that addr from usbhid and then bind it to our driver.
set -euo pipefail

name=$(basename $0)
DEFAULT_DRIVER="usbhid"
### KEEP this UPDATED ! ################################################
# 0d8d:1516 Promotion & Display Technology, Ltd Wireless Present   (PDL)
MY_DRIVER="laserp"
MY_DRIVER_LOC=/home/kaiwan/gitL3/usb/laser_prsnt_input_usb
MYUSB_VID=0D8D
MYUSB_PID=1516
#########################################################################

red_highlight()
{
  [[ $# -eq 0 ]] && return
  echo -e "\e[1m\e[41m$1\e[0m"
}

die()
{
 echo >&2 "${name}:FATAL: $*" ; exit 1
}

unbind()
{
local USB_DEVICE=$1
echo "Unbinding ${USB_DEVICE} from ${DEFAULT_DRIVER}"
sudo sh -c "echo -n ${USB_DEVICE} > /sys/bus/usb/drivers/${DEFAULT_DRIVER}/unbind"
if [ $? -ne 0 ]
then
	echo -e "\e[1m\e[41m[ERROR] Could not unbind:" $err "\e[0m"
	echo "The reason for this might be: "
	echo "(*)Device has already been unbound from" ${DEFAULT_DRIVER}
	echo "(*)${DEFAULT_DRIVER} is not responsible for this device"
	echo "(*)${USB_DEVICE} is not the correct USB device"
	return 1
fi
return 0
}

bind()
{
local USB_DEVICE=$1
echo "Binding $1 to ${MY_DRIVER}"
#err=$(sudo sh -c 'echo -n ${USB_DEVICE} > /sys/bus/usb/drivers/${MY_DRIVER}/bind' 2>&1)
sudo sh -c "echo -n ${USB_DEVICE} > /sys/bus/usb/drivers/${MY_DRIVER}/bind"
#if [ ! -z "$err" ]
if [ $? -ne 0 ]
then
	echo "[ERROR] Could not bind:" $err
	echo "The reason for this might be: "
	echo "(*)Device has already been bound to ${MY_DRIVER}"
	echo "(*)${MY_DRIVER} does not support this device"
	return 1
fi
return 0
}

# $1 : the USB usbhid driver's bus address
check_id_bind_on_match()
{
local MYUSB_VID=${MYUSB_VID^^} # to uppercase
local MYUSB_PID=${MYUSB_PID^^}
local USB_DEVICE="$1"

# Auto check
if [[ -f /sys/bus/usb/drivers/${DEFAULT_DRIVER}/${USB_DEVICE}/modalias ]] ; then
 # the 'modalias' looks like this (for example):
 # usb:v0D8Dp1516d1110dc00dsc00dp00ic03isc01ip02in00

 local UVID=$(cut -d: -f2 /sys/bus/usb/drivers/${DEFAULT_DRIVER}/${USB_DEVICE}/modalias |cut -c2-5)
 local UPID=$(cut -d: -f2 /sys/bus/usb/drivers/${DEFAULT_DRIVER}/${USB_DEVICE}/modalias |cut -c7-10)
 #echo "(FYI: for provided bus/device VID:PID is ${UVID}:${UPID}"
 lsusb | grep -i "${UVID}:${UPID}" || {
   echo "No USB device match, aborting" ; return 1
 }
 if [[ "${UVID}" = "${MYUSB_VID}" ]] && [[ "${UPID}" = "${MYUSB_PID}" ]] ; then
   echo " MATCH, proceeding"
   FOUND=1
   lsusb | grep -i "${UVID}:${UPID}" >/dev/null || {  # re-confirm it's there (??)
     echo "No USB device match, aborting" ; return 1
   }
   unbind ${USB_DEVICE} || return 1
   sleep .1
   bind ${USB_DEVICE} || return 1
 fi
fi
}


#--- 'main'

lsmod|grep ${MY_DRIVER} >/dev/null || {
  # Verify it's installed, else install it
  ls /lib/modules/$(uname -r)/updates/${MY_DRIVER}.ko* >/dev/null 2>&1 || {
     NOT_INSTALLED=1
     ls /lib/modules/$(uname -r)/extra/${MY_DRIVER}.ko* >/dev/null 2>&1 && NOT_INSTALLED=0
  }
  [[ ${NOT_INSTALLED} -eq 1 ]] && (cd ${MY_DRIVER_LOC} ; sudo make install)
  sudo modprobe ${MY_DRIVER} ${KMOD_PARAMS} || die "modprobe ${MY_DRIVER} failed? Insert your \"${MY_DRIVER}\" driver first and retry"
}

[[ 0 -eq 1 ]] && {
[[ $# -ne 1 ]] && {
  echo "Usage: $0 <usb-bus-#>
F.e. $0 1-2:1.0
(TIPs: 
  - Check under /sys/bus/usb/drivers/${DEFAULT_DRIVER} and/or look up dmesg
  - Just specify the first of the bus addresses as the argument (f.e. rebind 1-2:1.0)"
  res=$(ls -1d /sys/bus/usb/drivers/${DEFAULT_DRIVER}/[0-9]* 2>/dev/null) || true
  [[ -z "${res}" ]] && echo "Currently there aren't any (under /sys/bus/usb/drivers/${DEFAULT_DRIVER})" || echo "
Here's the currently assigned bus addresses:

${res}
"
#  exit 1
}
}

res=$(ls -1d /sys/bus/usb/drivers/${DEFAULT_DRIVER}/[0-9]* 2>/dev/null) || true
[[ -z "${res}" ]] && die "Currently there aren't any (under /sys/bus/usb/drivers/${DEFAULT_DRIVER})"

FOUND=0
echo "=== Now checking all USB devices on the \"${DEFAULT_DRIVER}\" USB bus"
for usbbus in ${res}
do
  USB_BUS=$(basename ${usbbus})
  echo "--- USB bus = ${USB_BUS}"
  check_id_bind_on_match ${USB_BUS}
  [[ ${FOUND} -eq 1 ]] && break
done

[[ ${FOUND} -eq 0 ]] && {
  red_highlight "*** ${name}: the laser presenter USB device for this driver \"${MY_DRIVER}\" isn't plugged in? Aborting... ***"
  echo "(If it's there, try unplugging, then re-inserting the USB device and then retry)"
  exit 1
} || {
  echo ">>> ${name}: done, device driven by \"${MY_DRIVER}\" is now ready to use! <<<"
  exit 0
}
